MCLOUD-5953: Backport Redis patches
magento/magento-cloud-patches pull request #46
Opened 2020-05-11 20:24 UTC by BaDos

### Description

### Fixed Issues (if relevant)
https://jira.corp.magento.com/browse/MCLOUD-5953

### Manual testing scenarios

1. ...
2. ...

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

2020-05-11 21:21 UTC, BarnyShergold requested changes
Please add description from ticket MCLOUD-5953 to this PR's description. Not all Reviewers have access to the JIRA ticket.

2020-05-11 21:21 UTC, BarnyShergold commented on patches.json
> +    },
Remove space

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-22950__large_amount_of_keys_block_cache__2.3.1.patch
> ++
Remove extra line break

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++                "Cache frontend '{$identifier}' is not recognized. As well as " .
Don't embed variables in strings - use sprintf if required

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++    public function load($id, $doNotTestCacheValidity = false)
Return type after prototype missing

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++     * @param  string  $id                     Cache id
Remove extra whitespace

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++    public function save($data, $id, $tags = [], $specificLifetime = false)
Return type after prototype missing

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++ * This class created for correct work witch local caches and multiple web nodes,
witch SHOULD BE with?

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++ * This class will be check cache version from remote cache and in case it newer
insert 'is' after it

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++ * than local one, it will update local one from remote cache a.k.a two level cache.
Please don't use acronyms in comments - some non-native English speakers might not know what it means

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++    private function getDataVersion(string $data)
Return type after prototype missing

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++    private function loadRemoteDataVersion(string $id)
Return type after prototype missing

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++    private function saveRemoteDataVersion(string $data, string $id, array $tags, $specificLifetime = false)
Return type after prototype missing

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++    private function removeRemoteDataVersion($id)
Return type after prototype missing

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++    public function doOperation()
Return type after prototype missing

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++    public function getName()
Return type after prototype missing

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++        return 'App action list generation';
Should be a constant

2020-05-11 21:21 UTC, BarnyShergold commented on patches/MDVA-26795__fix_performance_issue_in_cache_locking_mechanism__2.3.4.patch
> ++    public function getName()
Where does this method ever get called?

2020-05-26 16:06 UTC, oshmyheliuk approved these changes

2020-05-27 14:11 UTC, arhiopterecs approved these changes

2020-06-03 19:17 UTC, andriyShevtsov commented
QA approved

2020-06-03 19:25 UTC, andriyShevtsov commented
@BarnyShergold Thank you for review. Unfortunately we are not able to change patches. It was provided by core team and already a part of magento next release. Changes in patches on our side may broke something.

2020-06-03 20:28 UTC, shiftedreality commented
@BarnyShergold, please approve

2020-06-03 21:15 UTC, BarnyShergold approved these changes
Accepted with acknowledgement to why patch cannot be changed

2020-06-04 13:32 UTC, merged