Patch for BUNDLE-2670
magento/magento-cloud-patches pull request #65
Opened 2020-07-29 21:56 UTC by magterskine

Patch for https://jira.corp.magento.com/browse/BUNDLE-2670

2020-07-30 00:45 UTC, BarnyShergold requested changes
The is no proper description for the PR - please add one with correct format and full description
Tests are failing

2020-07-30 16:14 UTC, viktym commented
Please, fix patch filename (use __ after ticket number and before the version):
```
  Correct format: <TICKET_NUMBER>__<TITLE>__<PACKAGE_VERSION>.patch                                 
  Example: MAGECLOUD-2899__fix_redis_slave_configuration__2.3.0.patch  
```

2020-07-30 18:37 UTC, shiftedreality commented
@viktym @magterskine please re-create this PR into https://github.com/magento/quality-patches

2020-07-30 23:54 UTC, BarnyShergold submitted a review, later dismissed

2020-08-04 15:08 UTC, NadiyaS commented on patches/BUNDLE-2670__braintree_virtual_terminal_ui_fix__4.1.0.patch
> +index 0000000..efb2e66
Please remove index. It is redundant information.

2020-08-04 15:14 UTC, NadiyaS commented on patches/BUNDLE-2670__braintree_virtual_terminal_ui_fix__4.1.0.patch
> +                     }
Please add an empty line at the end

2020-08-04 15:25 UTC, shiftedreality requested changes

2020-08-04 15:25 UTC, shiftedreality commented on patches/BUNDLE-2670__braintree_virtual_terminal_ui_fix__4.1.0.patch
> +diff --git a/vendor/paypal/module-braintree-core/view/adminhtml/web/css/source/_module.less b/vendor/paypal/module-braintree-core/view/adminhtml/web/css/source/_module.less
Please use `diff -Naur`

2020-08-04 15:25 UTC, shiftedreality commented on patches/BUNDLE-2670__braintree_virtual_terminal_ui_fix__4.1.0.patch
> +diff --git a/vendor/paypal/module-braintree-core/view/adminhtml/web/js/virtual.js b/vendor/paypal/module-braintree-core/view/adminhtml/web/js/virtual.js
Please use `diff -Naur`

2020-08-04 19:16 UTC, magterskine commented on patches/BUNDLE-2670__braintree_virtual_terminal_ui_fix__4.1.0.patch
> +                     }
Done

2020-08-04 20:32 UTC, NadiyaS approved these changes

2020-08-04 20:34 UTC, shiftedreality approved these changes

2020-08-07 17:23 UTC, BaDos commented
FT fails:

```Applying patch BUNDLE-2670 (/app/vendor/magento/magento-cloud-patches/patches/BUNDLE-2670__braintree_virtual_terminal_ui_fix__4.1.0.patch) failed.
Error Output:
================
error: vendor/paypal/module-braintree-core/view/adminhtml/web/css/source/_module.less: already exists in working directory
Patch BUNDLE-2670 can't be applied to clean Magento instance
[2020-08-07 17:19:09] ERROR: [12] The command "php ./vendor/bin/ece-patches apply --no-interaction" failed. Error: patch conflict happened
Applying patch BUNDLE-2670 (/app/vendor/magento/magento-cloud-patches/patches/BUNDLE-2670__braintree_virtual_terminal_ui_fix__4.1.0.patch) failed.
Error Output:
================
error: vendor/paypal/module-braintree-core/view/adminhtml/web/css/source/_module.less: already exists in working directory
Patch BUNDLE-2670 can't be applied to clean Magento instance
```

2020-08-10 11:00 UTC, BarnyShergold approved these changes

2020-08-10 21:02 UTC, BaDos commented
@magterskine Please check your patch.
There is some conflicts.

```Applying patch BUNDLE-2670 (/app/vendor/magento/magento-cloud-patches/patches/BUNDLE-2670__braintree_virtual_terminal_ui_fix__4.1.0.patch) failed.
Error Output:
================
error: vendor/paypal/module-braintree-core/view/adminhtml/web/css/source/_module.less: already exists in working directory
Patch BUNDLE-2670 can't be applied to clean Magento instance
[2020-08-10 18:38:47] ERROR: [12] The command "php ./vendor/bin/ece-patches apply --no-interaction" failed. Patch MCLOUD-6659 has been applied
Title: Redis improvements
File: MCLOUD-6659__fix_L2_redis_cache__2.4.0.patch
Affected components: magento/framework
Error: patch conflict happened
Start of rollback
Patch MCLOUD-6659 has been reverted
End of rollback
Applying patch BUNDLE-2670 (/app/vendor/magento/magento-cloud-patches/patches/BUNDLE-2670__braintree_virtual_terminal_ui_fix__4.1.0.patch) failed.
Error Output:
================
error: vendor/paypal/module-braintree-core/view/adminhtml/web/css/source/_module.less: already exists in working directory
Patch BUNDLE-2670 can't be applied to clean Magento instance
returned non-zero exit status 12  Time 01:49
```

2020-08-25 15:43 UTC, shiftedreality commented
@rganin please re-open this PR once it's ready for review

2020-08-25 15:43 UTC, closed without merging