B2B-716: Exception thrown during setup:upgrade when installing B2B
magento/magento-cloud-patches pull request #70
Opened 2020-08-04 19:17 UTC by rganin

### Description
Patch for https://jira.corp.magento.com/browse/B2B-716

### Fixed Issues (if relevant)

1. https://jira.corp.magento.com/browse/B2B-716

### Manual testing scenarios

1. ...
2. ...

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud Patches release notes](https://devdocs.magento.com/cloud/release-notes/mcp-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes and documentation changes
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)

2020-08-05 17:45 UTC, NadiyaS commented on patches/B2B-716-Exception_thrown_during_upgrade_when_installing_B2B_2.4.0.patch
> +index c8acaa346..6579e8812 100644
remove redundant index

2020-08-05 17:45 UTC, NadiyaS requested changes
Add this patch to `patches.json`

2020-08-06 18:45 UTC, NadiyaS commented on patches.json
> +      "2.4.0": "B2B-716-Exception_thrown_during_upgrade_when_installing_B2B_2.4.0.patch"
please use double underscore after ticket number and after name
So the name of patch should look like `B2B-716__exception_thrown_during_upgrade_when_installing_B2B__2.4.0.patch`

2020-08-10 10:59 UTC, BarnyShergold requested changes
Please add proper description to the PR - A link to a Magento JIRA ticket can't be used as many Maintainers don't have access to the JIRA instance.

2020-08-10 13:47 UTC, shiftedreality commented
@rganin please address highlighted issues

2020-08-25 15:43 UTC, shiftedreality commented
@rganin please re-open this PR once it's ready for review

2020-08-25 15:43 UTC, closed without merging